name: Build et déploiement Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: check url
      run: echo ${REGISTRY_URL}

    - name: Connexion au registre Docker
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${REGISTRY_URL}

    - name: Obtenir la date et l'heure actuelles
      run: |
        export CURRENT_DATETIME=$(date '+%Y%m%d%H%M%S')

    - name: Construction de l'image Docker
      run: docker build -t ictest:$CURRENT_DATETIME .

    - name: Exécution du conteneur Docker
      run: docker run -p 8080:80 ictest:$CURRENT_DATETIME

    - name: Tag de l'image Docker
      run: docker tag ictest:$CURRENT_DATETIME ${REGISTRY_URL}/ictest:$CURRENT_DATETIME

    - name: Push de l'image Docker vers le registre
      run: docker push ${REGISTRY_URL}/ictest:$CURRENT_DATETIME
