name: Build et déploiement Docker

on:
  push:
    branches:
      - main
env:
  REGISTRY_URL: "docker.io"
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: check url
      run: echo ${{ env.REGISTRY_URL }}

    - name: Construction de l'image Docker
      run: docker build -t ictest:$CURRENT_DATETIME .

    - name: Exécution du conteneur Docker
      run: docker run -p 8080:80 ictest:$CURRENT_DATETIME

    - name: Tag de l'image Docker
      run: docker tag ictest:$CURRENT_DATETIME ${REGISTRY_URL}/ictest:$CURRENT_DATETIME
