name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  variableGlobal: "Je suis une variable accessible dans tout le workflow"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      variableJob1: "Je suis une variable accessible dans tout le job"
    steps:
    - name: Exemple Hello world
      run: echo "Hello World !"
    - name: Exemple d'utilisation de variable d'environnement de la step
      env:
        MY_VARIABLE: "Hello, World!"
      run: echo $MY_VARIABLE
    - name: Exemple de récuperation du nom du trigger
      run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - name: Exemple de récuperation du nom de l'environnement host
      run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - name: Exemple de récuperation du nom de la branch et du repository
      run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Exemple d'utilisation de variable d'environnement global
      run: echo $variableGlobal
    - name: Exemple d'utilisation de variable d'environnement du job
      run: echo $variableJob1
    - name: Exemple d'utilisation de variable d'environnement de la step 2
      if: ${{ env.MY_VARIABLE == "Hello, World!" }}
      run: echo "My_variable a la bonne valeur"
    - name: Exemple d'utilisation de variable d'environnement de la step 2 2
      if: ${{ env.MY_VARIABLE != 'Hello, World!' }}
      run: echo "La variable a pas la bonne valeur"
