name: Tests avec différentes versions de Node.js

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x, 12.x, 10.x]

    runs-on: ubuntu-latest

    steps:
    - name: Utiliser Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Check la version
      run: node -v
